services:
  system:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - test-postgres
    env_file:
      - .env
    
  test-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
    ports:
      - "5434:5432"