services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/backend:/CRM/apps/backend

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./apps/frontend:/CRM/apps/frontend

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test-postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_PORT: ${DB_PORT_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASSWORD_TEST}
    ports:
      - "5434:${DB_PORT_TEST}"

volumes:
  pgdata: