name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_commit_naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit messages
        uses: tim-actions/commit_message-checker-with-regex@v1
        with:
          regex: '^(feat|fix|docs|style|refactor|perf|test|chore|ci|build|revert)(\([\w\s\-]+\))?: .{1,50}'
          error_message: 'Commit messages must follow the Conventional Commits format. Example: "feat(module): add new feature"'

  check_code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run lint checks
        run: npm run check-lint

  check_builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --production

      - name: Build apps
        run: npm run build

  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
