name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_commit_naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check commit messages
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|perf|test|chore|ci|cd)(\([\w\s]+\))?: .{1,50}'
          error: 'Commit message does not follow the conventional format.'

  check_code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run lint checks
        run: npm run check-lint

  check_builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Build apps
        run: npm run build

  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Set up .env file
        run: cp .env.example .env

      - name: Build and run test containers
        run: docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
